=== bearsunday/BEAR.Resource/docs/schema/semantic-log.json
{
  "$schema": "http://json-schema.org/draft-07/schema#",
  "$id": "/Users/akihito/git/BEAR.Resource/docs/schema/semantic-log.json",
  "title": "BEAR.Resource Semantic Log",
  "description": "Complete semantic log structure for BEAR.Resource framework execution tracing",
  "links": [
    {
      "rel": "https://bearsunday.github.io/BEAR.Resource/docs/link-relations#ai-docs",
      "title": "BEAR.Resource Framework Overview for AI",
      "href": "/Users/akihito/git/BEAR.Resource/docs/llms.txt"
    },
    {
      "rel": "service-doc",
      "title": "BEAR.Resource Complete Documentation",
      "href": "/Users/akihito/git/BEAR.Resource/docs/llms-full.txt"
    },
    {
      "rel": "about",
      "title": "BEAR.Resource Project",
      "href": "https://bearsunday.github.io/BEAR.Resource/"
    }
  ],
  "type": "object",
  "properties": {
    "schemaUrl": {
      "type": "string",
      "description": "URL of the semantic log schema"
    },
    "open": {
      "description": "Resource request initiation context",
      "$ref": "/Users/akihito/git/BEAR.Resource/docs/schema/open-context.json"
    },
    "close": {
      "description": "Resource request completion context", 
      "$ref": "/Users/akihito/git/BEAR.Resource/docs/schema/complete-context.json"
    },
    "error": {
      "description": "Resource request error context",
      "$ref": "/Users/akihito/git/BEAR.Resource/docs/schema/error-context.json"
    },
    "events": {
      "type": "array",
      "description": "Array of events that occurred during execution"
    },
    "links": {
      "type": "array", 
      "description": "Array of hypermedia links related to this execution"
    }
  },
  "required": ["schemaUrl"],
  "additionalProperties": true
}

=== bearsunday/BEAR.Resource/demo/tmp/semantic-logs/semantic-dev-2025-08-08_21-55-44-000000-87083-6896726060303.json
{
    "schemaUrl": "https://koriym.github.io/Koriym.SemanticLogger/schemas/combined.json",
    "open": {
        "id": "bear_resource_request_1",
        "type": "bear_resource_request",
        "schemaUrl": "https://bearsunday.github.io/BEAR.Resource/schemas/open-context.json",
        "context": {
            "method": "POST",
            "uri": "app://self/user?name=D%27Artagnan&age=18",
            "call": [
                "MyVendor\\Demo\\Resource\\App\\User",
                "onPost"
            ]
        }
    },
    "close": {
        "id": "bear_resource_complete_1",
        "type": "bear_resource_complete",
        "schemaUrl": "https://bearsunday.github.io/BEAR.Resource/schemas/complete-context.json",
        "context": {
            "uri": "app://self/user?name=D%27Artagnan&age=18",
            "code": 201,
            "headers": {
                "Content-Type": "application/json"
            },
            "body": {
                "name": "D'Artagnan",
                "age": 18,
                "blog_id": 3
            },
            "view": "{\n    \"name\": \"D'Artagnan\",\n    \"age\": 18,\n    \"blog_id\": 3\n}\n",
            "profile": {
                "xhprof": {
                    "source": "/var/folders/bc/r8s1n7x93md3t_r6mqpy9xj40000gn/T/xhprof_2025-08-08_21-55-44_1431252f8006e3807686d09b695a0c31.json"
                },
                "xdebug": {
                    "source": "/tmp/profile_6896726059acf6.39752517",
                    "file_size": 131985,
                    "compressed": false
                },
                "php": {
                    "backtrace": [
                        {
                            "function": "collectBacktrace",
                            "file": "/Users/akihito/git/Koriym.SemanticLogger/src/Profiler/PhpProfile.php",
                            "line": 51,
                            "class": "Koriym\\SemanticLogger\\Profiler\\PhpProfile",
                            "type": "::"
                        },
                        {
                            "function": "capture",
                            "file": "/Users/akihito/git/BEAR.Resource/src/SemanticLog/Profile/Verbose/CompleteContext.php",
                            "line": 58,
                            "class": "Koriym\\SemanticLogger\\Profiler\\PhpProfile",
                            "type": "::"
                        },
                        {
                            "function": "__construct",
                            "file": "/Users/akihito/git/BEAR.Resource/src/SemanticLog/Profile/Verbose/CompleteContext.php",
                            "line": 72,
                            "class": "BEAR\\Resource\\SemanticLog\\Profile\\Verbose\\CompleteContext",
                            "type": "->"
                        },
                        {
                            "function": "create",
                            "file": "/Users/akihito/git/BEAR.Resource/src/SemanticLog/Profile/Verbose/ContextFactory.php",
                            "line": 26,
                            "class": "BEAR\\Resource\\SemanticLog\\Profile\\Verbose\\CompleteContext",
                            "type": "::"
                        },
                        {
                            "function": "createCompleteContext",
                            "file": "/Users/akihito/git/BEAR.Resource/src/SemanticLog/DevSemanticInvoker.php",
                            "line": 41,
                            "class": "BEAR\\Resource\\SemanticLog\\Profile\\Verbose\\ContextFactory",
                            "type": "->"
                        },
                        {
                            "function": "invoke",
                            "file": "/Users/akihito/git/BEAR.Resource/src/AbstractRequest.php",
                            "line": 135,
                            "class": "BEAR\\Resource\\SemanticLog\\DevSemanticInvoker",
                            "type": "->"
                        },
                        {
                            "function": "__invoke",
                            "file": "/Users/akihito/git/BEAR.Resource/src/Resource.php",
                            "line": 123,
                            "class": "BEAR\\Resource\\AbstractRequest",
                            "type": "->"
                        },
                        {
                            "function": "post",
                            "file": "/Users/akihito/git/BEAR.Resource/demo/6.semantic-log.php",
                            "line": 52,
                            "class": "BEAR\\Resource\\Resource",
                            "type": "->"
                        }
                    ],
                    "wall_time": 0,
                    "total_wall_time": 0
                }
            }
        },
        "openId": "bear_resource_request_1"
    },
    "events": [],
    "links": []
}

=== bearsunday/BEAR.Resource/demo/tmp/semantic-logs/semantic-dev-2025-08-07_01-13-42-000000-45391-6893fdc680456.json
{
    "schemaUrl": "https://koriym.github.io/Koriym.SemanticLogger/schemas/semantic-log.json",
    "open": {
        "id": "bear_resource_request_1",
        "type": "bear_resource_request",
        "$schema": "https://bearsunday.github.io/BEAR.Resource/schemas/open-context.json",
        "context": {
            "method": "POST",
            "uri": "app://self/user?name=D%27Artagnan&age=18",
            "call": [
                "MyVendor\\Demo\\Resource\\App\\User",
                "onPost"
            ]
        }
    },
    "close": {
        "id": "bear_resource_complete_1",
        "type": "bear_resource_complete",
        "$schema": "https://bearsunday.github.io/BEAR.Resource/schemas/complete-context.json",
        "context": {
            "uri": "app://self/user?name=D%27Artagnan&age=18",
            "code": 201,
            "headers": {
                "Location": "app://self/user?id=3",
                "Content-Type": "application/json"
            },
            "body": {
                "name": "D'Artagnan",
                "age": 18,
                "blog_id": 3
            },
            "view": "{\n    \"name\": \"D'Artagnan\",\n    \"age\": 18,\n    \"blog_id\": 3\n}\n",
            "profile": {
                "xhprof": {
                    "file": null,
                    "functions_count": 0,
                    "total_wall_time": 0
                },
                "xdebug": {
                    "file": null,
                    "file_size": 0,
                    "compressed": false
                },
                "php": {
                    "backtrace": [
                        {
                            "function": "collectBacktrace",
                            "file": "/Users/akihito/git/Koriym.SemanticLogger/src/Profiler/PhpProfile.php",
                            "line": 30,
                            "class": "Koriym\\SemanticLogger\\Profiler\\PhpProfile",
                            "type": "::"
                        },
                        {
                            "function": "capture",
                            "file": "/Users/akihito/git/BEAR.Resource/src/SemanticLog/Profile/Verbose/CompleteContext.php",
                            "line": 58,
                            "class": "Koriym\\SemanticLogger\\Profiler\\PhpProfile",
                            "type": "::"
                        },
                        {
                            "function": "__construct",
                            "file": "/Users/akihito/git/BEAR.Resource/src/SemanticLog/Profile/Verbose/CompleteContext.php",
                            "line": 72,
                            "class": "BEAR\\Resource\\SemanticLog\\Profile\\Verbose\\CompleteContext",
                            "type": "->"
                        },
                        {
                            "function": "create",
                            "file": "/Users/akihito/git/BEAR.Resource/src/SemanticLog/Profile/Verbose/ContextFactory.php",
                            "line": 26,
                            "class": "BEAR\\Resource\\SemanticLog\\Profile\\Verbose\\CompleteContext",
                            "type": "::"
                        },
                        {
                            "function": "createCompleteContext",
                            "file": "/Users/akihito/git/BEAR.Resource/src/SemanticLog/DevSemanticInvoker.php",
                            "line": 41,
                            "class": "BEAR\\Resource\\SemanticLog\\Profile\\Verbose\\ContextFactory",
                            "type": "->"
                        },
                        {
                            "function": "invoke",
                            "file": "/Users/akihito/git/BEAR.Resource/src/AbstractRequest.php",
                            "line": 135,
                            "class": "BEAR\\Resource\\SemanticLog\\DevSemanticInvoker",
                            "type": "->"
                        },
                        {
                            "function": "__invoke",
                            "file": "/Users/akihito/git/BEAR.Resource/src/Resource.php",
                            "line": 123,
                            "class": "BEAR\\Resource\\AbstractRequest",
                            "type": "->"
                        },
                        {
                            "function": "post",
                            "file": "/Users/akihito/git/BEAR.Resource/demo/semantic-log.php",
                            "line": 76,
                            "class": "BEAR\\Resource\\Resource",
                            "type": "->"
                        }
                    ]
                }
            }
        },
        "openId": "bear_resource_request_1"
    },
    "events": [],
    "links": []
}

=== bearsunday/BEAR.Resource/demo/tmp/semantic-logs/semantic-dev-2025-08-07_01-33-22-000000-52707-68940262257d1.json
{
    "schemaUrl": "https://koriym.github.io/Koriym.SemanticLogger/schemas/semantic-log.json",
    "open": {
        "id": "bear_resource_request_1",
        "type": "bear_resource_request",
        "$schema": "https://bearsunday.github.io/BEAR.Resource/schemas/open-context.json",
        "context": {
            "method": "GET",
            "uri": "app://self/user?id=1",
            "call": [
                "MyVendor\\Demo\\Resource\\App\\User",
                "onGet"
            ]
        }
    },
    "close": {
        "id": "bear_resource_complete_1",
        "type": "bear_resource_complete",
        "$schema": "https://bearsunday.github.io/BEAR.Resource/schemas/complete-context.json",
        "context": {
            "uri": "app://self/user?id=1",
            "code": 200,
            "headers": {
                "Content-Type": "application/json"
            },
            "body": {
                "name": "Aramis",
                "age": 16,
                "blog_id": 1
            },
            "view": "{\n    \"name\": \"Aramis\",\n    \"age\": 16,\n    \"blog_id\": 1\n}\n",
            "profile": {
                "xhprof": {
                    "file": null,
                    "functions_count": 0,
                    "total_wall_time": 0
                },
                "xdebug": {
                    "file": null,
                    "file_size": 0,
                    "compressed": false
                },
                "php": {
                    "backtrace": [
                        {
                            "function": "collectBacktrace",
                            "file": "/Users/akihito/git/Koriym.SemanticLogger/src/Profiler/PhpProfile.php",
                            "line": 30,
                            "class": "Koriym\\SemanticLogger\\Profiler\\PhpProfile",
                            "type": "::"
                        },
                        {
                            "function": "capture",
                            "file": "/Users/akihito/git/BEAR.Resource/src/SemanticLog/Profile/Verbose/CompleteContext.php",
                            "line": 58,
                            "class": "Koriym\\SemanticLogger\\Profiler\\PhpProfile",
                            "type": "::"
                        },
                        {
                            "function": "__construct",
                            "file": "/Users/akihito/git/BEAR.Resource/src/SemanticLog/Profile/Verbose/CompleteContext.php",
                            "line": 72,
                            "class": "BEAR\\Resource\\SemanticLog\\Profile\\Verbose\\CompleteContext",
                            "type": "->"
                        },
                        {
                            "function": "create",
                            "file": "/Users/akihito/git/BEAR.Resource/src/SemanticLog/Profile/Verbose/ContextFactory.php",
                            "line": 26,
                            "class": "BEAR\\Resource\\SemanticLog\\Profile\\Verbose\\CompleteContext",
                            "type": "::"
                        },
                        {
                            "function": "createCompleteContext",
                            "file": "/Users/akihito/git/BEAR.Resource/src/SemanticLog/DevSemanticInvoker.php",
                            "line": 41,
                            "class": "BEAR\\Resource\\SemanticLog\\Profile\\Verbose\\ContextFactory",
                            "type": "->"
                        },
                        {
                            "function": "invoke",
                            "file": "/Users/akihito/git/BEAR.Resource/src/AbstractRequest.php",
                            "line": 135,
                            "class": "BEAR\\Resource\\SemanticLog\\DevSemanticInvoker",
                            "type": "->"
                        },
                        {
                            "function": "__invoke",
                            "file": "/Users/akihito/git/BEAR.Resource/src/Resource.php",
                            "line": 114,
                            "class": "BEAR\\Resource\\AbstractRequest",
                            "type": "->"
                        },
                        {
                            "function": "get",
                            "file": "/Users/akihito/git/BEAR.Resource/demo/6.semantic-log.php",
                            "line": 49,
                            "class": "BEAR\\Resource\\Resource",
                            "type": "->"
                        }
                    ]
                }
            }
        },
        "openId": "bear_resource_request_1"
    },
    "events": [],
    "links": []
}

=== bearsunday/BEAR.Resource/demo/ai-test/simple-semantic-log.json
{
    "schemaUrl": "https://koriym.github.io/Koriym.SemanticLogger/schemas/semantic-log.json",
    "open": {
        "id": "bear_resource_request_1",
        "type": "bear_resource_request",
        "$schema": "https://bearsunday.github.io/BEAR.Resource/schemas/open-context.json",
        "context": {
            "method": "GET",
            "uri": "app://self/simple?id=test-123"
        }
    },
    "close": {
        "id": "bear_resource_complete_1",
        "type": "bear_resource_complete",
        "$schema": "https://bearsunday.github.io/BEAR.Resource/schemas/complete-context.json",
        "context": {
            "uri": "app://self/simple?id=test-123",
            "code": 200,
            "headers": {
                "Content-Type": "application/json"
            },
            "body": {
                "id": "test-123",
                "message": "Hello from Simple",
                "timestamp": 1754130153
            },
            "view": "{\n    \"id\": \"test-123\",\n    \"message\": \"Hello from Simple\",\n    \"timestamp\": 1754130153\n}\n"
        },
        "openId": "bear_resource_request_1"
    },
    "events": [],
    "links": []
}

=== bearsunday/BEAR.Resource/demo/fake-semantic-log-with-issues.json
{
    "schemaUrl": "https://koriym.github.io/Koriym.SemanticLogger/schemas/semantic-log.json",
    "open": {
        "id": "bear_resource_request_1",
        "type": "bear_resource_request",
        "$schema": "https://bearsunday.github.io/BEAR.Resource/schemas/open-context.json",
        "context": {
            "method": "GET",
            "uri": "app://self/user/list?page=1"
        }
    },
    "events": [
        {
            "id": "db_query_1",
            "type": "database_query",
            "timestamp": "2025-01-01T10:00:00.100Z",
            "context": {
                "query": "SELECT * FROM users WHERE active = 1",
                "duration_ms": 15.2,
                "rows_returned": 100
            }
        },
        {
            "id": "db_query_2",
            "type": "database_query",
            "timestamp": "2025-01-01T10:00:00.120Z",
            "context": {
                "query": "SELECT * FROM profiles WHERE user_id = 1",
                "duration_ms": 8.5,
                "rows_returned": 1
            }
        },
        {
            "id": "db_query_3",
            "type": "database_query",
            "timestamp": "2025-01-01T10:00:00.135Z",
            "context": {
                "query": "SELECT * FROM profiles WHERE user_id = 2",
                "duration_ms": 8.3,
                "rows_returned": 1
            }
        },
        {
            "id": "db_query_100",
            "type": "database_query",
            "timestamp": "2025-01-01T10:00:01.200Z",
            "context": {
                "query": "SELECT * FROM profiles WHERE user_id = 100",
                "duration_ms": 12.1,
                "rows_returned": 1
            }
        },
        {
            "id": "cache_miss_1",
            "type": "cache_operation",
            "timestamp": "2025-01-01T10:00:01.250Z",
            "context": {
                "operation": "get",
                "key": "user_permissions_1",
                "result": "miss",
                "duration_ms": 2.1
            }
        },
        {
            "id": "external_api_1",
            "type": "http_request",
            "timestamp": "2025-01-01T10:00:01.300Z",
            "context": {
                "url": "https://api.example.com/permissions/1",
                "method": "GET",
                "status_code": 200,
                "duration_ms": 450.5
            }
        }
    ],
    "close": {
        "id": "bear_resource_complete_1",
        "type": "bear_resource_complete",
        "$schema": "https://bearsunday.github.io/BEAR.Resource/schemas/complete-context.json",
        "context": {
            "uri": "app://self/user/list?page=1",
            "code": 200,
            "headers": {
                "Content-Type": "application/json"
            },
            "body": {
                "users": "... (100 users with profiles)",
                "total": 100,
                "page": 1
            },
            "view": "{\"users\":[...],\"total\":100,\"page\":1}",
            "xhprofFile": "/tmp/xhprof_app___self_user_list_page=1_demo123.xhprof",
            "xdebugTraceFile": "/tmp/xdebug_trace_demo123.xt.gz",
            "total_duration_ms": 1250.8,
            "memory_peak_mb": 45.2
        },
        "openId": "bear_resource_request_1"
    },
    "links": []
}
